### ISSUE TITLE
SDK treats ~ as if it is a special directory

### ISSUE THREAD

**Issue by Qix-** [WootingKb/wooting-analog-sdk#1]
The SDK appears to be using `~` in path names on MacOS as if they are handled specially by the system. Instead, it looks in the CWD for a directory literally called `~` (e.g. via `mkdir \~`) instead.

Output looks like this (last line is from my utility):

```
[2019-08-30T15:44:46Z ERROR wooting_analog_sdk::sdk] Error: Error(Msg("Path: \"~/.analog_plugins\" is not a dir!"), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
error: could not initialize sdk: no plugins
```

After making the directory relative to the CWD...

```shell
$ mkdir -p \~/.analog_plugins
```

.... running it again removed that first error message:

```
error: could not initialize sdk: no plugins
```

Here's the sample code I'm working with.

```c
#include <wooting-analog-wrapper.h>

#include <stdio.h>

static const char * wooting_error(WootingAnalogResult res) {
	switch (res) {
		case WootingAnalogResult_Ok: return "OK (no error)";
		case WootingAnalogResult_UnInitialized: return "wooting SDK uninitialized";
		case WootingAnalogResult_NoDevices: return "no devices";
		case WootingAnalogResult_DeviceDisconnected: return "device disconnected";
		case WootingAnalogResult_Failure: return "operation failed";
		case WootingAnalogResult_InvalidArgument: return "invalid argument";
		case WootingAnalogResult_NoPlugins: return "no plugins";
		case WootingAnalogResult_FunctionNotFound: return "function not found";
		case WootingAnalogResult_NoMapping: return "no mapping";
		case WootingAnalogResult_NotAvailable: return "not available";
		default: return "unknown error";
	}
}

int main(void) {
	int status = 1;
	WootingAnalogResult res;

	res = wooting_analog_initialise();
	if (res != WootingAnalogResult_Ok) {
		fprintf(stderr, "error: could not initialize sdk: %s\n", wooting_error(res));
		goto exit;
	}

	status = 0;

exit:
	return status;
}
```

This is happening because `~` is not a special character used by the UNIX/BSD filesystem subsystem. It's more correct to manually pull the `HOME` environment variable via e.g. `getenv()` (or some Rust equivalent) and use that instead.

Note that I do not have `WOOTING_ANALOG_SDK_PLUGINS_PATH` set, so there's a default being substituted in somewhere.

**Comment by simon-wh** [comment]
The default value for `WOOTING_ANALOG_SDK_PLUGINS_PATH` should probably be removed, as  it was originally put there as just a placeholder. Device plugins are required for the SDK to work, so you should install the [wooting plugin](https://github.com/WootingKb/wooting-analog-plugin) and set the `WOOTING_ANALOG_SDK_PLUGINS_PATH` var to the path where you put the plugin DLL.

**Comment by simon-wh** [comment]
The SDK has changed to only loading from subdirectories of 
Win: `C:\Program Files\WootingAnalogPlugins`
Linux: `/usr/local/share/WootingAnalogPlugins`
Mac: `/Library/WootingAnalogPlugins`
So that plugins cannot be loaded from user writable directories to prevent the possibility of easy unauthorised code execution

**Comment by PastaJ36** [comment]
Will that folder be a loose collection of dynamic libraries or do we expect custom / other vendor plugins to adhere to some folder structure?

**Comment by Qix-** [comment]
Right now it resembles VST folders, which are a single level of loadable DLL's. I think that's as good as it gets unless plugins need auxiliary files required but the SDK, which isn't the case.
