### ISSUE TITLE
Is Analog SDK API actual?

### ISSUE THREAD

**Issue by sergei-z** [WootingKb/wooting-analog-sdk#2]
I'm trying to resolve symbols from DLL, using API description from https://dev.wooting.io/wooting-analog-sdk-guide/analog-api-description/, but it always fails.

That is, I've tried to resolve `wooting_read_analog `symbol, but it failed. After that I opened the library in the Dependancy Walker and saw that there are no functions specified in the API, but there are similar ones. There is `wooting_analog_read_analog` instead of `wooting_read_analog` and there is no `wooting_kbd_connected ` function at all. So the question is Analog SDK API actual?

**Comment by simon-wh** [comment]
The guides on the website are outdated and are for https://github.com/WootingKb/wooting-analog-sdk-old

Please use the API as described [here](https://github.com/WootingKb/wooting-analog-sdk/blob/master/SDK_USAGE.md)
