### ISSUE TITLE
deb package for v0.7

### ISSUE THREAD

**Issue by cwhy** [WootingKb/wooting-analog-sdk#25]
In the v0.7 release, it seems that the deb package is missing? :thinking:

**Comment by simon-wh** [comment]
Appears the deployment messed up somewhere with it, I'll have a look into it. Do you need it now or are you grand?

**Comment by cwhy** [comment]
Thanks for the reply, I am not in a rush to use it. I can use the Windows version meanwhile

**Comment by simon-wh** [comment]
There's a Debian package available for the latest v0.7.1 release
