### ISSUE TITLE
[Request] Wooting 80HE Support

### ISSUE THREAD

**Issue by tylernguyen** [WootingKb/wooting-analog-sdk#87]
Hi,

Now that the first batch of 80HE have been out for a while, it would be great if it can be supported by the analog SDK.

**Comment by simon-wh** [comment]
Hey, sorry for the wait, there were a few issues blocking getting a new Analog SDK update out, but these are pretty much all resolved now. 

https://github.com/WootingKb/wooting-analog-sdk/releases/tag/v0.8.0

v0.8.0 release is out now which supports the 80HE 😁
